spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdatabase
    username: test
    password: test1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6397

jwt:
  secret: dagdjakltjlnsdg;kjt;jdntkjdkahtkkdngkl
  access-token-expire-time: 24 * 60 * 60 * 100L * 14
  refresh-token-expire-time: 24 * 60 * 60 * 1000L * 14;

aws-property:
  s3-bucket-name: now-sopt-bucket2
  access-key: AKIAZI2LDN4LBMYGX4EP
  secret-key: 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
  aws-region: ap-northeast-2
